//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace User_Management_System_V2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public string Description { get; set; }
        public int PriceExpected { get; set; }
        public int OldTime { get; set; }
        public int Status { get; set; }
        public byte[] Photo { get; set; }
        public string PostedBy { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string RequestedBy { get; set; }
        public Nullable<System.DateTime> RequestedByDatenTime { get; set; }
    }
}
